# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-06 13:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': '新闻类别',
                'verbose_name_plural': '新闻类别',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '新闻评论',
                'verbose_name_plural': '新闻评论',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.IntegerField(verbose_name='新闻id')),
                ('s_title', models.CharField(max_length=200, verbose_name='小标题')),
                ('s_ab', models.CharField(max_length=200, verbose_name='小导读')),
                ('img_url', models.CharField(max_length=200, verbose_name='图片地址')),
                ('time', models.CharField(max_length=200, verbose_name='新闻时间')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('abstrat', models.CharField(max_length=200, verbose_name='导读')),
                ('content', models.TextField(default='', verbose_name='正文')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='count.Category', verbose_name='文章类别')),
            ],
            options={
                'verbose_name': '新闻内容',
                'verbose_name_plural': '新闻内容',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='avator_sor',
        ),
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.IntegerField(default=0, verbose_name='金币'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='count.News', verbose_name='新闻'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
