# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-17 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0005_findpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='abstrat',
            field=models.CharField(max_length=255, verbose_name='导读'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img_url',
            field=models.CharField(max_length=255, verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_id',
            field=models.IntegerField(max_length=255, verbose_name='新闻id'),
        ),
        migrations.AlterField(
            model_name='news',
            name='s_ab',
            field=models.CharField(max_length=255, verbose_name='小导读'),
        ),
        migrations.AlterField(
            model_name='news',
            name='s_title',
            field=models.CharField(max_length=255, verbose_name='小标题'),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.CharField(max_length=255, verbose_name='新闻时间'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='标题'),
        ),
    ]
