# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-12 03:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_auto_20190812_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='C_user',
        ),
        migrations.AddField(
            model_name='questions',
            name='C_user',
            field=models.ManyToManyField(null=True, related_name='questions_collection_set', to=settings.AUTH_USER_MODEL, verbose_name='收藏者'),
        ),
        migrations.RemoveField(
            model_name='questions',
            name='DL_user',
        ),
        migrations.AddField(
            model_name='questions',
            name='DL_user',
            field=models.ManyToManyField(null=True, related_name='questions_dislike_set', to=settings.AUTH_USER_MODEL, verbose_name='差评者'),
        ),
        migrations.RemoveField(
            model_name='questions',
            name='L_user',
        ),
        migrations.AddField(
            model_name='questions',
            name='L_user',
            field=models.ManyToManyField(null=True, related_name='questions_like_set', to=settings.AUTH_USER_MODEL, verbose_name='点赞者'),
        ),
    ]
