# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-13 02:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0003_auto_20190812_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='收藏/取消时间')),
                ('status', models.BooleanField(default=True, verbose_name='收藏状态')),
            ],
            options={
                'verbose_name': '收藏记录',
                'verbose_name_plural': '收藏记录',
            },
        ),
        migrations.CreateModel(
            name='Questionsliker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='喜欢/取消时间')),
                ('status', models.BooleanField(default=True, verbose_name='喜欢状态')),
            ],
            options={
                'verbose_name': '喜欢记录',
                'verbose_name_plural': '喜欢记录',
            },
        ),
        migrations.RemoveField(
            model_name='questions',
            name='C_user',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='DL_user',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='L_user',
        ),
        migrations.AddField(
            model_name='questionsliker',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Questions', verbose_name='问题'),
        ),
        migrations.AddField(
            model_name='questionsliker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='喜欢者'),
        ),
        migrations.AddField(
            model_name='questionscollection',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Questions', verbose_name='问题'),
        ),
        migrations.AddField(
            model_name='questionscollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收藏者'),
        ),
    ]
