# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-17 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='imgurl',
            field=models.CharField(max_length=100, verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='video',
            name='titles',
            field=models.CharField(max_length=100, verbose_name='视频标题'),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoid',
            field=models.CharField(max_length=101, verbose_name='视频id'),
        ),
    ]
