# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-12 02:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='题目')),
                ('content', models.CharField(max_length=100, null=True, verbose_name='题目解析')),
                ('answer', models.CharField(max_length=100, null=True, verbose_name='题目答案')),
                ('choose_A', models.CharField(max_length=100, verbose_name='A选项')),
                ('choose_B', models.CharField(max_length=100, verbose_name='B选项')),
                ('choose_C', models.CharField(max_length=100, verbose_name='C选项')),
                ('choose_D', models.CharField(max_length=100, verbose_name='D选项')),
                ('choose_E', models.CharField(max_length=100, verbose_name='E选项')),
                ('C_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_collection_set', to=settings.AUTH_USER_MODEL, verbose_name='收藏者')),
                ('DL_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_dislike_set', to=settings.AUTH_USER_MODEL, verbose_name='差评者')),
                ('L_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_like_set', to=settings.AUTH_USER_MODEL, verbose_name='点赞者')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '题库',
                'permissions': (('can_change_question', '可以修改题目信息'), ('can_add_question', '可以添加题目信息')),
            },
        ),
    ]
