# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-12 03:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='C_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_collection_set', to=settings.AUTH_USER_MODEL, verbose_name='收藏者'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='DL_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_dislike_set', to=settings.AUTH_USER_MODEL, verbose_name='差评者'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='L_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_like_set', to=settings.AUTH_USER_MODEL, verbose_name='点赞者'),
        ),
    ]
