# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-06 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0003_auto_20190806_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.CharField(max_length=100, verbose_name='金币'),
        ),
    ]
