# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-16 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=8, verbose_name='视频标题')),
                ('imgurl', models.CharField(max_length=20, verbose_name='图片地址')),
                ('videoid', models.CharField(max_length=11, verbose_name='视频id')),
            ],
        ),
    ]
